# Generated by Django 4.2.2 on 2023-07-01 08:04

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userprofile_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=account.models.get_profile_image_filepath),
        ),
    ]
