# Generated by Django 4.2.2 on 2023-06-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_adress_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
