# Generated by Django 4.2.2 on 2023-06-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
